### PR TITLE
Update runtime to 23.08, libglu to 9.0.3, libpng to 1.6.41.

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Sadly does not run:

screenshot

This is on stdout:

```
named_colours.xml:24: parser error : Growing input buffer
<colour name="popup.optiontextmouseover" r="1.0" g="1.0" b="1.0" a="1.0"/>
                                                                        ^
languages/en/strings/console.xml:83: parser error : Growing input buffer
     <markpos>markpos</markpos>
                     ^
languages/en/strings/console.xml:83: parser error : Growing input buffer
     <markpos>markpos</markpos>
                     ^
languages/en/strings/errors.xml:168: parser error : Growing input buffer
      <accept>I Accept</accept>
                              ^
languages/en/strings/errors.xml:168: parser error : Growing input buffer
      <accept>I Accept</accept>
                              ^
languages/en/strings/help.xml:139: parser error : Growing input buffer
      <logon>%.*s has logged on.</logon>
                                ^
languages/en/strings/help.xml:139: parser error : Growing input buffer
      <logon>%.*s has logged on.</logon>
                                ^
languages/en/strings/options.xml:302: parser error : Growing input buffer
 Manufacture, Storage and Inventory windows to appear above the map and console.
                                                                               ^
languages/en/strings/options.xml:302: parser error : Growing input buffer
 Manufacture, Storage and Inventory windows to appear above the map and console.
                                                                               ^
languages/en/strings/spells.xml:95: parser error : Growing input buffer
      </remove>
              ^
languages/en/strings/spells.xml:95: parser error : Growing input buffer
      </remove>
              ^
languages/en/strings/stats.xml:157: parser error : Growing input buffer
         <shortname>eng</shortname>
                                  ^
languages/en/strings/stats.xml:157: parser error : Growing input buffer
         <shortname>eng</shortname>
                                  ^
languages/en/strings/titles.xml:44: parser error : Growing input buffer
      <tab_adv_video>Adv Video</tab_adv_video>
                              ^
languages/en/strings/titles.xml:44: parser error : Growing input buffer
      <tab_adv_video>Adv Video</tab_adv_video>
                              ^
mines.xml:18: parser error : Growing input buffer
	<mine id="7" type="Mana drainer">./3dobjects/ward1.e3d</mine>
	                                ^
sound/snds_enviro.xml:498: parser error : Growing input buffer
	<stereo>1</stereo>
	                 ^
sound/sound_config.xml:30: parser error : Entity 'snds_enviro' failed to parse
	&snds_enviro;
	             ^
sound/sound_config.xml:321: parser error : Growing input buffer
	<sound name = "Poison">
	       ^
actor_defs/player_standard.xml:1: parser error : Growing input buffer
	<ghost>no</ghost>
^
actor_defs/playerav_human_female.xml:84: parser error : Entity 'standard_players' failed to parse
	&standard_players;
	                  ^
actor_defs/playerav_human_female.xml:135: parser error : Growing input buffer
		<torso>./meshes/torso_skinhf_tan.dds</torso>		
		      ^
actor_defs/actor_defs.xml:141: parser error : Entity 'human_female' failed to parse
	&human_female;
	              ^
actor_defs/actor_defs.xml:233: parser error : Growing input buffer
	&dragon2_gray;
	              ^
emotes.xml:460: parser error : Growing input buffer
	<CAL_emote_sit index="1000">./animations/player_idle1.caf 0</CAL_emote_sit>
	^
actor_defs/missile_defs.xml:78: parser error : Growing input buffer
  </missile>
           ^
./weather.xml:19: parser error : Growing input buffer
    <density>1.0</density>
                         ^
./spells.xml:361: parser error : Growing input buffer
	<sigil id="21" name="Protection">protection</sigil>
	       ^
languages/en/Encyclopedia/index.xml:21: parser error : Growing input buffer
   <Category>Miscellanea</Category>
                                  ^
languages/en/strings/channels.xml:50: parser error : Growing input buffer
	<channel number="4900" name="Russian">Chat in Russian</channel>
	                      ^
languages/en/strings/channels.xml:50: parser error : Growing input buffer
	<channel number="4900" name="Russian">Chat in Russian</channel>
	                      ^
languages/en/rules.xml:206: parser error : Growing input buffer
eas detailed above, can result in permanent banishment from the forums and game.
                                                                               ^
languages/en/rules.xml:206: parser error : Growing input buffer
eas detailed above, can result in permanent banishment from the forums and game.
                                                                               ^
The rules.xml file was not found. You will have to redownload your game.
```

**Comment by AsciiWolf** [comment]
screenshot

Works fine now. :-) @pjbroad Feel free to merge.

**Comment by pjbroad** [comment]
Hi @AsciiWolf.  The libxml2 issue is known and fixed in the latest client source.  The libxml2 authors implemented feature to enable using a bigger buffer for parsing, but there were other changes to libxml that required client changes.  Also the current runtime used is still supported so I was not intending to move to a newer version just yet.  Perhaps for the beta stream we could use a newer runtime and the latest client source.

**Comment by AsciiWolf** [comment]
Hi @pjbroad. Thanks for the info! I will close this PR, feel free to create a new PR for the beta branch and use my changes there. :-)

**Pull request closed without merging**
